apiVersion: v1
kind: Secret
metadata:
  name: {{ include "request-tracker.secretName" . }}
  labels:
    {{- include "request-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ include "request-tracker.databasePassword" . | b64enc | quote }}
  root-password: {{ .Values.rt.rootPassword | b64enc | quote }}
  {{- if .Values.msmtp.password }}
  msmtp-password: {{ .Values.msmtp.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.getmail.password }}
  getmail-password: {{ .Values.getmail.password | b64enc | quote }}
  {{- end }}
