apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "itop.fullname" . }}-php-config
  labels:
    {{- include "itop.labels" . | nindent 4 }}
data:
  redis-session.ini: |
    {{- .Values.phpConfig.redisSession | nindent 4 }}
